apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
patchesStrategicMerge:
- go-sample/deployment.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: go-sample-ingress
    namespace: demo
  path: go-sample/ingress_patch.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: web-ingress
    namespace: linkerd
  path: monitoring/linkerd_dashboard_patch.yaml
    