apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.36
  name: nginx
  namespace: nginx-ingress
spec:
  chart:
    name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.36.2
  releaseName: nginx