apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
  labels:
    chart: podinfo
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:0.4
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:stefanprodan/podinfo
    path: charts/podinfo
    ref: master
  values:
    image: stefanprodan/podinfo:0.4.10
    replicaCount: 3