apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "podinfo-ingress"   
  labels:
    app: "podinfo-ingress"  
  namespace: demo
spec:
  rules:
    - host: "dvd-info.rdps-emea.rackspace.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: podinfo
              servicePort: 9898