apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  labels:
    app: go-sample2
  name: go-sample2
  annotations:
    fluxcd.io/locked: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample2
  strategy: {}
  template:
    metadata:
      labels:
        app: go-sample2
    spec:
      containers:
      - image: gcr.io/devops-ps-uk-default/david-go-sample:0.1
        name: go-sample2
        resources: {}
      # imagePullSecrets:
      #   - name: gcr-json-key
---
  
apiVersion: v1
kind: Service
metadata:
  name: go-sample2
  namespace: demo
  labels:
    app: go-sample2
spec:
  selector:
    app: go-sample2
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP