piVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  creationTimestamp: null
  labels:
    app: nginx2
  name: nginx2
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nginx2: semver:~1.17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx:1.17.9
        name: nginx2
        resources: {}
status: {}