---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  creationTimestamp:
  labels:
    app: nginx
  name: nginx
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nginx2: semver:~1.17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.18-alpine-perl
        name: nginx
        resources: {}
status: {}
