apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: demo
  labels:
    app: nginx2
spec:
  type: LoadBalancer
  selector:
    app: nginx2
  ports:
  - name: http
    port: 80
    protocol: TCP