apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- go-sample/deployment.yaml
- go-sample/service.yaml
- demo-ns.yaml
- helm-releases/nginx.yaml
- helm-releases/external-dns.yaml